apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcomemicroservice
spec:
  selector:
    matchLabels:
      app: welcomemicroservice
  replicas: 1
  template:
    metadata:
      labels:
        app: welcomemicroservice
    spec:
      containers:
      - name: welcomemicroservice
        image: welcome_dashboard_image
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent